/**
 * Copyright (c) 2014 - 2019, Nordic Semiconductor ASA
 * All rights reserved.
 * This file contains code to run the ECG + IMU sensor project. It is based on
 * the interrupts generated by the ADS1299 device (from the DRDY pins) to collect and
 * transmit the data over BLE to the central device. It also collects IMU sensor data
 * from the ICM20649 device and transmits in a similar fashion.
 */

#include "nordic_common.h"
#include "app_error.h"
#include "app_timer.h"
#include "ble_srv_common.h"
#include "nrf_log.h"
#include "nrf_log_ctrl.h"
#include "nrf_delay.h"
#include "nrf_drv_gpiote.h"

/* User defined includes */
#include "usr_config.h"
#include "ble_usr_defined.h"
#include "nrf_usr_defined.h"

/* Variable to indicated whether the device is currently connected to a BLE central device */
bool m_connected = false;

#if defined(ADS1299)
#include "ads1299-x.h"
#include "ble_eeg.h"
ble_eeg_t m_eeg[NUM_OF_ADS1299] = {0};
#define SPI_SCLK_WRITE_REG      1
#define SPI_SCLK_SAMPLING       1 // old value = 1
#endif /* #if defined(ADS1299) */

#if defined(ICM20649)
#include "icm20649.h"
#include "ble_icm.h"
ble_icm_t m_icm[NUM_OF_ICM_DEVICES] = {0};
#endif

APP_TIMER_DEF(m_sampling_timer_id);
#define TICKS_SAMPLING_INTERVAL APP_TIMER_TICKS(1000)
#if defined(ICM20649)
APP_TIMER_DEF(m_icm_timer_id);
#define ICM_SAMPLING_INTERVAL   APP_TIMER_TICKS(20)
#endif

/* Number of samples recorded in a time interval (BLE) */
static uint16_t m_samples[NUM_OF_ADS1299] = {0};
#if defined(ADS1299)
static volatile uint32_t m_drdy_last_tick[NUM_OF_ADS1299];
static volatile uint32_t m_drdy_avg_period_us[NUM_OF_ADS1299];
static volatile bool m_drdy_seen_once[NUM_OF_ADS1299];
#endif

#if defined(ADS1299)
static uint32_t app_timer_ticks_to_us(uint32_t ticks)
{
    /* APP_TIMER runs from LFCLK (usually 32768 Hz). */
    return (uint32_t)(((uint64_t)ticks * 1000000ULL + (APP_TIMER_CLOCK_FREQ / 2u)) / APP_TIMER_CLOCK_FREQ);
}

static void drdy_interval_update(uint8_t dev_idx)
{
    uint32_t now_ticks = app_timer_cnt_get();

    if (dev_idx >= NUM_OF_ADS1299)
    {
        return;
    }

    if (!m_drdy_seen_once[dev_idx])
    {
        m_drdy_seen_once[dev_idx] = true;
        m_drdy_last_tick[dev_idx] = now_ticks;
        return;
    }

    uint32_t diff_ticks = app_timer_cnt_diff_compute(now_ticks, m_drdy_last_tick[dev_idx]);
    m_drdy_last_tick[dev_idx] = now_ticks;

    uint32_t interval_us = app_timer_ticks_to_us(diff_ticks);
    if (interval_us == 0u)
    {
        return;
    }

    /* Exponential moving average with alpha = 1/8. */
    if (m_drdy_avg_period_us[dev_idx] == 0u)
    {
        m_drdy_avg_period_us[dev_idx] = interval_us;
    }
    else
    {
        m_drdy_avg_period_us[dev_idx] =
            (uint32_t)((7u * m_drdy_avg_period_us[dev_idx] + interval_us) / 8u);
    }
}
#endif

#if defined(SAADC_ENABLED) && SAADC_ENABLED == 1
#include "nrf_drv_saadc.h"
#define SAMPLES_IN_BUFFER       4
#define SAADC_BURST_MODE        1 // Set to 1 to enable BURST mode, otherwise set to 0.
static nrf_saadc_value_t m_buffer_pool[SAMPLES_IN_BUFFER];
static uint32_t m_adc_evt_counter;
#endif

#if defined(BLE_BAS_ENABLED) && BLE_BAS_ENABLED == 1
#include "ble_bas2.h"
static ble_bas_t m_bas;
// Timer stuff:
APP_TIMER_DEF(m_battery_timer_id);
#define BATTERY_TIMER_INTERVAL  APP_TIMER_TICKS(60000) /**< Battery level measurement interval (ticks). */
#endif

#if defined(BLE_DIS_ENABLED) && BLE_DIS_ENABLED == 1
#include "ble_dis.h"
#endif

/*! @brief Periodic diagnostics callback for sample-rate logging.
 * @param[in] p_context  Unused context pointer.
 * @return None.
 */
static void m_sampling_timeout_handler(void *p_context)
{
    UNUSED_PARAMETER(p_context);
#if defined(ADS1299)
    for (uint8_t i = 0; i < NUM_OF_ADS1299; i++)
    {
        NRF_LOG_INFO("Device %u SAMPLE RATE = %dHz | DRDY avg us: = %u",
                    i, m_samples[i], (uint32_t)m_drdy_avg_period_us[i]);
        m_samples[i] = 0;
    }
#endif
}

#if defined(ICM20649)
/*! @brief Timer callback to read ICM20649 sample data every 5 ms.
 * Reads raw accel/gyro/temp bytes into the BLE sample buffer and transmits when
 * the packet buffer is full.
 * @param[in] p_context  Unused context pointer.
 * @return None.
 */
static void icm_timer_timeout_handler(void *p_context)
{
    UNUSED_PARAMETER(p_context);
    if (!m_connected || (m_icm[0].conn_handle == BLE_CONN_HANDLE_INVALID)) {
        return;
    }

    const uint16_t bytes_per_sample = ICM20649_SAMPLE_RAW_LEN;
    const uint16_t max_samples = (uint16_t)(sizeof(m_icm[0].icm_sample_buffer) / bytes_per_sample);

    if (m_icm[0].icm_sample_count >= max_samples) {
        ble_icm_update_sample(&m_icm[0]);
        if (m_icm[0].icm_sample_count >= max_samples) {
            return;
        }
    }
    /* Calclate the offset at whwich the new recorded data should be stored in the buffer */
    uint16_t offset = (uint16_t)(m_icm[0].icm_sample_count * bytes_per_sample);
    ret_code_t err = icm20649_read_sample(&m_icm20649[0],
                                          &m_icm[0].icm_sample_buffer[offset],
                                          NULL);
    if (err != NRF_SUCCESS) {
        NRF_LOG_WARNING("ICM read failed: 0x%X", err);
        return;
    }
    /* Increment the samples recorded */
    m_icm[0].icm_sample_count++;
    if (m_icm[0].icm_sample_count >= max_samples) {
        /* Transmit collected data to BLE central device */
        ble_icm_update_sample(&m_icm[0]);
    }
}
#endif

#if defined(BLE_BAS_ENABLED) && BLE_BAS_ENABLED == 1
/*! @brief Trigger one battery-level SAADC measurement.
 * @return None.
 */
static void battery_level_update(void)
{
    nrf_gpio_pin_set(BATTERY_LOAD_SWITCH_CTRL_PIN);
    nrf_drv_saadc_sample();
}

/*! @brief Periodic timer callback for battery measurements.
 * @param[in] p_context  Unused context pointer.
 * @return None.
 */
static void battery_timeout_handler(void *p_context)
{
    UNUSED_PARAMETER(p_context);
    battery_level_update();
}
#endif /* #if defined(BLE_BAS_ENABLED) && BLE_BAS_ENABLED == 1 */

/*! @brief Function for the Timer initialization.
 * @details Initializes the timer module. This creates and starts application timers.
 * @return None.
 */
static void timers_init(void)
{
    // Initialize timer module.
    ret_code_t err_code = app_timer_init();
    APP_ERROR_CHECK(err_code);
    // Create timers.
#if defined(BLE_BAS_ENABLED) && BLE_BAS_ENABLED == 1
    err_code = app_timer_create(&m_battery_timer_id, APP_TIMER_MODE_REPEATED, battery_timeout_handler);
    APP_ERROR_CHECK(err_code);
#endif
#if defined(ICM20649)
    err_code = app_timer_create(&m_icm_timer_id, APP_TIMER_MODE_REPEATED, icm_timer_timeout_handler);
    APP_ERROR_CHECK(err_code);
#endif
    err_code = app_timer_create(&m_sampling_timer_id, APP_TIMER_MODE_REPEATED, m_sampling_timeout_handler);
    APP_ERROR_CHECK(err_code);
}

/*! @brief Initialize all enabled BLE services.
 * @return None.
 */
static void services_init(void)
{
    ret_code_t err_code;
#if defined(ADS1299)
    ble_eeg_init_t init[NUM_OF_ADS1299];
    init[0].eeg_config_handler = eeg_config_handler;
#if (NUM_OF_ADS1299 == 2)
    init[1].eeg_config_handler = eeg_config_handler;
#endif

    ble_eeg_service_init(&m_eeg[0], &init[0]);
#if (NUM_OF_ADS1299 == 2)
    ble_eeg_service_init(&m_eeg[1], &init[1]);
#endif
#endif

#if defined(ICM20649)
    ble_icm_init_t icm_init = {0};
    icm_init.icm_config_handler = icm_config_handler;
    for (uint8_t i = 0; i < NUM_OF_ICM_DEVICES; i++)
    {
        m_icm[i].dev_idx = i;
        ble_icm_service_init(&m_icm[i], &icm_init);
    }
#endif

#if defined(BLE_BAS_ENABLED) && BLE_BAS_ENABLED == 1
    ble_bas_init_t bas_init;
    // Initialize Battery Service.
    memset(&bas_init, 0, sizeof(bas_init));

    bas_init.evt_handler = NULL;
    bas_init.support_notification = true;
    bas_init.p_report_ref = NULL;
    bas_init.initial_batt_level = 100;

    // Here the sec level for the Battery Service can be changed/increased.
    bas_init.bl_rd_sec = SEC_OPEN;
    bas_init.bl_cccd_wr_sec = SEC_OPEN;
    bas_init.bl_report_rd_sec = SEC_OPEN;

    err_code = ble_bas_init(&m_bas, &bas_init);
    APP_ERROR_CHECK(err_code);
#endif
#if defined(BLE_DIS_ENABLED) && BLE_DIS_ENABLED == 1
    ble_dis_init_t dis_init;
    // Initialize Device Information Service.
    memset(&dis_init, 0, sizeof(dis_init));

    ble_srv_ascii_to_utf8(&dis_init.manufact_name_str, (char *)MANUFACTURER_NAME);
    ble_srv_ascii_to_utf8(&dis_init.model_num_str, (char *)DEVICE_MODEL_NUMBERSTR);
    ble_srv_ascii_to_utf8(&dis_init.fw_rev_str, (char *)DEVICE_FIRMWARE_STRING);

    dis_init.dis_char_rd_sec = SEC_OPEN;

    err_code = ble_dis_init(&dis_init);
    APP_ERROR_CHECK(err_code);
#endif
}

/*! @brief Function for starting timers.
 * @return None.
 */
static void application_timers_start(void)
{
    ret_code_t err_code;
#if defined(BLE_BAS_ENABLED) && BLE_BAS_ENABLED == 1
    err_code = app_timer_start(m_battery_timer_id, BATTERY_TIMER_INTERVAL, NULL);
    APP_ERROR_CHECK(err_code);
#endif
#if defined(ICM20649)
    err_code = app_timer_start(m_icm_timer_id, ICM_SAMPLING_INTERVAL, NULL);
    APP_ERROR_CHECK(err_code);
#endif

    err_code = app_timer_start(m_sampling_timer_id, TICKS_SAMPLING_INTERVAL, NULL);
    APP_ERROR_CHECK(err_code);
}

#if defined(SAADC_ENABLED) && SAADC_ENABLED == 1
/*! @brief SAADC event callback for battery conversion completion.
 * @param[in] p_event  SAADC event payload.
 * @return None.
 */
void saadc_callback(nrf_drv_saadc_evt_t const *p_event)
{
    if (p_event->type == NRF_DRV_SAADC_EVT_DONE)
    {
        ret_code_t err_code;
        uint8_t battery_level = 0;
        err_code = nrf_drv_saadc_buffer_convert(p_event->data.done.p_buffer, SAMPLES_IN_BUFFER);
        APP_ERROR_CHECK(err_code);

        int i;
        NRF_LOG_INFO("ADC event number: %d\r\n", (int)m_adc_evt_counter);

        for (i = 3; i < SAMPLES_IN_BUFFER; i++)
        {
            NRF_LOG_INFO("Batt: 0x%x\r\n", p_event->data.done.p_buffer[i]);
        }
        // TRANSMIT UPDATED BATTERY VALUE.
        m_bas.battery_level = p_event->data.done.p_buffer[3];
        err_code = ble_bas_battery_level_update(&m_bas, p_event->data.done.p_buffer[3], BLE_CONN_HANDLE_ALL);
        if ((err_code != NRF_SUCCESS) &&
            (err_code != NRF_ERROR_INVALID_STATE) &&
            (err_code != NRF_ERROR_RESOURCES) &&
            (err_code != BLE_ERROR_GATTS_SYS_ATTR_MISSING))
        {
            APP_ERROR_HANDLER(err_code);
        }
        m_adc_evt_counter++;
        nrf_gpio_pin_clear(BATTERY_LOAD_SWITCH_CTRL_PIN); // LOAD SWITCH OFF
    }
}

/*! @brief Initialize SAADC resources for battery measurement.
 * @return None.
 */
void saadc_init(void)
{
    ret_code_t err_code;
    nrf_drv_saadc_config_t saadc_config;
    // Configure SAADC
    saadc_config.low_power_mode = true;                     // Enable low power mode.
    saadc_config.resolution = NRF_SAADC_RESOLUTION_12BIT;   // Set SAADC resolution to 12-bit. This will make the SAADC output values from 0 (when input voltage is 0V) to 2^12=2048 (when input voltage is 3.6V for channel gain setting of 1/6).
    saadc_config.oversample = NRF_SAADC_OVERSAMPLE_4X;      // Set oversample to 4x. This will make the SAADC output a single averaged value when the SAMPLE task is triggered 4 times.
    saadc_config.interrupt_priority = APP_IRQ_PRIORITY_LOW; // Set SAADC interrupt to low priority.

    nrf_saadc_channel_config_t channel_config =
        NRF_DRV_SAADC_DEFAULT_CHANNEL_CONFIG_SE(NRF_SAADC_INPUT_AIN2);

    err_code = nrf_drv_saadc_init(&saadc_config, saadc_callback);
    APP_ERROR_CHECK(err_code);

    err_code = nrf_drv_saadc_channel_init(0, &channel_config);
    APP_ERROR_CHECK(err_code);

    err_code = nrf_drv_saadc_buffer_convert(&m_buffer_pool[0], SAMPLES_IN_BUFFER);
    APP_ERROR_CHECK(err_code);
}
#endif /* #if defined(SAADC_ENABLED) && SAADC_ENABLED == 1 */

#if defined(ADS1299)
/*! @brief: This function will be called when DRDY signal is exerted.
 * @param[in] pin     GPIO pin that triggered the interrupt.
 * @param[in] action  GPIOTE edge action.
 * @return None.
 */
void ads_in_pin_handler(nrf_drv_gpiote_pin_t pin, nrf_gpiote_polarity_t action)
{
    UNUSED_PARAMETER(action);
    /* Check if the devices and bluetooth is connected */
    if (m_connected)
    {
        //drdy_interval_update(0u);
        if (pin == ADS1299_1_DRDY_PIN)
        {
            get_eeg_voltage_array_all_ch(&m_eeg[0]); // 1st ADS1299 device
            if (m_eeg[0].eeg_ch1_count == EEG_PACKET_LENGTH)
            {
                m_eeg[0].eeg_ch1_count = 0;
                ble_eeg_update_all_ch(&m_eeg[0]);
            }
            m_samples[0] += 1;
        }
#if (NUM_OF_ADS1299 == 2)
        if (pin == ADS1299_2_DRDY_PIN)
        { 
            //drdy_interval_update(1u);
            get_eeg_voltage_array_all_ch(&m_eeg[1]); // 2nd ADS1299 device
            // Once the buffer is completely filled
            if (m_eeg[1].eeg_ch1_count == EEG_PACKET_LENGTH)
            {
                // Reset the data counter to start refilling
                m_eeg[1].eeg_ch1_count = 0;
                ble_eeg_update_all_ch(&m_eeg[1]);
            }
            m_samples[1] += 1;
        }
#endif /* #if (NUM_OF_ADS1299 == 2) */
    }
}
#endif

static ret_code_t ads1299_init(void)
{
    /* Initialize global ADS1299 structrues */
    // ads_spi_init_with_sample_freq(SPI_SCLK_WRITE_REG);
    ads1299_spi_init_with_sample_freq(SPI_SCLK_SAMPLING);
    nrf_delay_ms(5);
    ads1299_powerdn();
    ads1299_powerup();

    /* Procedure (ADS1299):
        1. Wake
        2. Reset Device
        3. Wake device again
        4. Read all voltages (TEST MODE ONLY - NOT NECESSARY) ad device ID first
        5. Stop Continuous conversions
        6. Initialize all registers to required configurations
        7. Read all regsiters to verify written values.
        */
    for (uint8_t idx = 0; idx < NUM_OF_ADS1299; idx++)
    {
        ble_eeg_t *p_m_eeg = &m_eeg[idx];
        ads1299_wake(p_m_eeg);
        nrf_delay_ms(10);
        ads1299_reset(p_m_eeg);
        ads1299_wake(p_m_eeg);
        nrf_delay_ms(10);
        ads1299_stop_rdatac(p_m_eeg);
        ads1299_check_id(p_m_eeg);
        // Initialize ADS1299 devices and read back
        ads1299_init_regs_default(p_m_eeg);
        ads1299_read_all_registers(p_m_eeg);
        // NOTE: if you put 1st device in standby mode, then you cannot operate on 2nd ADS1299 device ads1299_standby(p_m_eeg);
        nrf_delay_ms(10);
        p_m_eeg->eeg_ch1_count = 0;
        NRF_LOG_FLUSH();
    }
    return NRF_SUCCESS;
}

/*! @brief Function for application main entry.
 * @return Application exit code (never reached in normal operation).
 */
int main(void)
{
    bool erase_bonds = false;
    // Initialize.
    log_init();
    /* INitialize required timers for the application */
    timers_init();
    /* nRF Power management module initializations */
    power_management_init();
    /* Initialize nRF GPIO Pins for interrupts/inputs/outputs */
    gpio_init();
#if defined(ADS1299)
    /* Initialize ADS device contexts before BLE service creation. */
    ads1299_struct_init();
#endif
    /* Initialize BLE stack*/
    ble_stack_init();
    /* Initialize GAP - Generic Attribute Profile */
    gap_params_init();
    /* Generic Attribute initialization */
    gatt_init();
    services_init();
    /* Initiale BLE advertisement and other PPCP parameters */
    advertising_init();
    conn_params_init();

#if (PEER_MANAGER_ENABLED == 1)
    peer_manager_init();
#endif

// Initialize SAADC
#if defined(SAADC_ENABLED) && SAADC_ENABLED == 1
    saadc_init();
#endif

#if defined(ICM20649)
    /* Initialize TWI interface. */
    twi_init();
    NRF_LOG_FLUSH();
#endif

#if defined(ADS1299)
    ads1299_init();
#endif /* #if defined(ADS1299) */

    NRF_LOG_INFO("ECG Device Advertising Start! \r\n");
    /* Start Adv BLE */
    application_timers_start();

    while (1) {
        /* Put device in no process mode until event (interrupt or timer) occurs to save power */
        while (m_connected) {__WFE(); NRF_LOG_FLUSH();}
        advertising_start(erase_bonds); // reconnect to BLE central if device disconnects
        while (!m_connected) {__WFE(); NRF_LOG_FLUSH();}
    }
}

/**
 * @}
 */
